### ISSUE TITLE
Items shown outside container

### ISSUE THREAD

**Issue by lamba92** [rintoj/ngx-virtual-scroller#316]
Well that's weird: https://giphy.com/embed/2imYfWJxJqM45FQCN9
I have no idea why:
```html
HTML

<mat-card class="logs-container">
  <mat-tab-group>
    <mat-tab *ngFor="let file of files | keyvalue" [label]="file.key">
        <virtual-scroller #scroller [items]="filteredItems(file.value)"></virtual-scroller>
        <ng-container *ngFor="let line of scroller.viewPortItems; let odd = odd">
          <p>{{line}}</p>
        </ng-container>
    </mat-tab>
  </mat-tab-group>
</mat-card>
```
```typescript
COMPONENT

files = new Map<string, string[]>();

filteredItems(items: string[]) {
  return items.filter((line: string) => {
    return this.checkIfDisplay(line)
  })
}
```
```scss
SCSS

p {
  padding: 2px;
  margin: 0;
}

.logs-container {
  margin: 16px;
}

virtual-scroller {
  width: 100%;
  height: 300px
}

```
