### ISSUE TITLE
virtual scroll doesn't work on safari

### ISSUE THREAD

**Issue by ranbuch** [rintoj/ngx-virtual-scroller#359]
[This url's](https://www.creators3d.com/offers) virtual scrolling works on Chrome but not on Safari.

This is how the component looks like:
```html
<div class="flexcontainer">
  <virtual-scroller #scroll [items]="items" fxLayout="row" fxLayoutAlign="space-between start"
    class="flex-wrap" [parentScroll]="scroll.window">
    <app-offer-card *ngFor="let item of scroll.viewPortItems; trackBy: trackByFn" [item]="item" fxFlex="100%"
      fxFlex.gt-sm="305px"></app-offer-card>
  </virtual-scroller>
</div>
```
```css
.flexcontainer {
    display: flex;
    flex-flow: row wrap;
    justify-content: space-around;
}
.flex-wrap {
    display: flex;
    flex-wrap: wrap;
}
html {
    height: 100%;
    display: block;
}
```

BTW I'm not using ```(vsEnd)``` event because it didn't work for me on Safari as well, probably for the same reason.

Any suggestions?
Thanks.
